name: CountWithKids
options:
  bundleIdPrefix: com.countwithkids
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 7PL4QQ4G6R
schemes:
  CountWithKids:
    build:
      targets:
        CountWithKids: all
        CountWithKidsTests: [test]
        CountWithKidsUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - CountWithKidsTests
        - CountWithKidsUITests
    archive:
      config: Release
targets:
  CountWithKids:
    type: application
    platform: iOS
    sources:
      - path: CountWithKids
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: com.countwithkids.app
        PRODUCT_NAME: "Count with Kids"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        SWIFT_EMIT_LOC_STRINGS: "YES"
  CountWithKidsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CountWithKidsTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: CountWithKids
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.countwithkids.app.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Count with Kids.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Count with Kids"
        BUNDLE_LOADER: "$(TEST_HOST)"
  CountWithKidsUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CountWithKidsUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: CountWithKids
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.countwithkids.app.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_TARGET_NAME: CountWithKids
