devices([
  "iPhone 16 Pro Max",
  "iPhone 15 Pro Max"
])

languages([
  "en-US",
  "cs",
  "he"
])

scheme("CountWithKids")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
